/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  RedstoneDefaultsLib,
  RedstoneDefaultsLibInterface,
} from "../RedstoneDefaultsLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "receivedTimestampSeconds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockTimestamp",
        type: "uint256",
      },
    ],
    name: "TimestampFromTooLongFuture",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "receivedTimestampSeconds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockTimestamp",
        type: "uint256",
      },
    ],
    name: "TimestampIsTooOld",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ceb00f7bb8b9dfe83dc530dcc444bc08c4e8d2c71ff254926581230e61675fb464736f6c63430008090033";

export class RedstoneDefaultsLib__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<RedstoneDefaultsLib> {
    return super.deploy(overrides || {}) as Promise<RedstoneDefaultsLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RedstoneDefaultsLib {
    return super.attach(address) as RedstoneDefaultsLib;
  }
  connect(signer: Signer): RedstoneDefaultsLib__factory {
    return super.connect(signer) as RedstoneDefaultsLib__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RedstoneDefaultsLibInterface {
    return new utils.Interface(_abi) as RedstoneDefaultsLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RedstoneDefaultsLib {
    return new Contract(address, _abi, signerOrProvider) as RedstoneDefaultsLib;
  }
}
