/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CustomUrlsConsumerBaseInterface extends ethers.utils.Interface {
  functions: {
    "aggregateValues(uint256[])": FunctionFragment;
    "extractTimestampsAndAssertAllAreEqual()": FunctionFragment;
    "getAuthorisedSignerIndex(address)": FunctionFragment;
    "getDataServiceId()": FunctionFragment;
    "getUniqueSignersThreshold()": FunctionFragment;
    "validateTimestamp(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aggregateValues",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "extractTimestampsAndAssertAllAreEqual",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorisedSignerIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataServiceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUniqueSignersThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateTimestamp",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "aggregateValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractTimestampsAndAssertAllAreEqual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorisedSignerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataServiceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniqueSignersThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTimestamp",
    data: BytesLike
  ): Result;

  events: {};
}

export class CustomUrlsConsumerBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CustomUrlsConsumerBaseInterface;

  functions: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { extractedTimestamp: BigNumber }>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getDataServiceId(overrides?: CallOverrides): Promise<[string]>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<[number]>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  aggregateValues(
    values: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  extractTimestampsAndAssertAllAreEqual(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAuthorisedSignerIndex(
    signerAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getDataServiceId(overrides?: CallOverrides): Promise<string>;

  getUniqueSignersThreshold(overrides?: CallOverrides): Promise<number>;

  validateTimestamp(
    receivedTimestampMilliseconds: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getDataServiceId(overrides?: CallOverrides): Promise<string>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<number>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDataServiceId(overrides?: CallOverrides): Promise<BigNumber>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDataServiceId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUniqueSignersThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
