/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TravelRedstoneOracleInterface extends ethers.utils.Interface {
  functions: {
    "aggregateValues(uint256[])": FunctionFragment;
    "extractTimestampsAndAssertAllAreEqual()": FunctionFragment;
    "fee()": FunctionFragment;
    "fulfillSLI(bytes32,uint256)": FunctionFragment;
    "fulfillsCounter()": FunctionFragment;
    "getAuthorisedSignerIndex(address)": FunctionFragment;
    "getDataServiceId()": FunctionFragment;
    "getOracleForSLA(address)": FunctionFragment;
    "getUniqueSignersThreshold()": FunctionFragment;
    "jobId()": FunctionFragment;
    "lpName()": FunctionFragment;
    "lpSymbol()": FunctionFragment;
    "lpSymbolSlaId(uint128)": FunctionFragment;
    "messengerPrecision()": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestSLI(uint256,address,bool,address)": FunctionFragment;
    "requestsCounter()": FunctionFragment;
    "retryRequest(address,uint256)": FunctionFragment;
    "setChainlinkJobID(bytes32,uint256)": FunctionFragment;
    "setDataFeedForSLA(address,bytes32)": FunctionFragment;
    "setSLARegistry()": FunctionFragment;
    "slaRegistryAddress()": FunctionFragment;
    "spName()": FunctionFragment;
    "spSymbol()": FunctionFragment;
    "spSymbolSlaId(uint128)": FunctionFragment;
    "testingOracleID()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "validateTimestamp(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aggregateValues",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "extractTimestampsAndAssertAllAreEqual",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillSLI",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillsCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorisedSignerIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataServiceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleForSLA",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniqueSignersThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "jobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpName", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpSymbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lpSymbolSlaId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "messengerPrecision",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSLI",
    values: [BigNumberish, string, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestsCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retryRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkJobID",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataFeedForSLA",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSLARegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slaRegistryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "spName", values?: undefined): string;
  encodeFunctionData(functionFragment: "spSymbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "spSymbolSlaId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testingOracleID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTimestamp",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "aggregateValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractTimestampsAndAssertAllAreEqual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fulfillSLI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillsCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorisedSignerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataServiceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleForSLA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniqueSignersThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpSymbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpSymbolSlaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messengerPrecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requestSLI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestsCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retryRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkJobID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDataFeedForSLA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSLARegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slaRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spSymbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spSymbolSlaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testingOracleID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTimestamp",
    data: BytesLike
  ): Result;

  events: {
    "DataFeedSetForSLA(address,bytes32)": EventFragment;
    "JobIdModified(address,bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SLIReceived(address,uint256,bytes32,bytes32)": EventFragment;
    "SLIRequested(address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DataFeedSetForSLA"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobIdModified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SLIReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SLIRequested"): EventFragment;
}

export type DataFeedSetForSLAEvent = TypedEvent<
  [string, string] & { slaAddress: string; oracle: string }
>;

export type JobIdModifiedEvent = TypedEvent<
  [string, string, BigNumber] & { owner: string; jobId: string; fee: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type SLIReceivedEvent = TypedEvent<
  [string, BigNumber, string, string] & {
    slaAddress: string;
    periodId: BigNumber;
    requestId: string;
    chainlinkResponse: string;
  }
>;

export type SLIRequestedEvent = TypedEvent<
  [string, BigNumber, string] & {
    caller: string;
    requestsCounter: BigNumber;
    requestId: string;
  }
>;

export class TravelRedstoneOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TravelRedstoneOracleInterface;

  functions: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { extractedTimestamp: BigNumber }>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    fulfillSLI(
      _requestId: BytesLike,
      _chainlinkResponse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fulfillsCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getDataServiceId(overrides?: CallOverrides): Promise<[string]>;

    getOracleForSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<[number]>;

    jobId(overrides?: CallOverrides): Promise<[string]>;

    lpName(overrides?: CallOverrides): Promise<[string]>;

    lpSymbol(overrides?: CallOverrides): Promise<[string]>;

    lpSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    messengerPrecision(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestSLI(
      _periodId: BigNumberish,
      _slaAddress: string,
      _ownerApproval: boolean,
      _callerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestsCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    retryRequest(
      _slaAddress: string,
      _periodId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setChainlinkJobID(
      arg0: BytesLike,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDataFeedForSLA(
      _slaAddress: string,
      _oracle: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSLARegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    slaRegistryAddress(overrides?: CallOverrides): Promise<[string]>;

    spName(overrides?: CallOverrides): Promise<[string]>;

    spSymbol(overrides?: CallOverrides): Promise<[string]>;

    spSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    testingOracleID(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  aggregateValues(
    values: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  extractTimestampsAndAssertAllAreEqual(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  fulfillSLI(
    _requestId: BytesLike,
    _chainlinkResponse: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fulfillsCounter(overrides?: CallOverrides): Promise<BigNumber>;

  getAuthorisedSignerIndex(
    signerAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getDataServiceId(overrides?: CallOverrides): Promise<string>;

  getOracleForSLA(
    _slaAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getUniqueSignersThreshold(overrides?: CallOverrides): Promise<number>;

  jobId(overrides?: CallOverrides): Promise<string>;

  lpName(overrides?: CallOverrides): Promise<string>;

  lpSymbol(overrides?: CallOverrides): Promise<string>;

  lpSymbolSlaId(
    slaId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  messengerPrecision(overrides?: CallOverrides): Promise<BigNumber>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestSLI(
    _periodId: BigNumberish,
    _slaAddress: string,
    _ownerApproval: boolean,
    _callerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestsCounter(overrides?: CallOverrides): Promise<BigNumber>;

  retryRequest(
    _slaAddress: string,
    _periodId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setChainlinkJobID(
    arg0: BytesLike,
    arg1: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDataFeedForSLA(
    _slaAddress: string,
    _oracle: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSLARegistry(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  slaRegistryAddress(overrides?: CallOverrides): Promise<string>;

  spName(overrides?: CallOverrides): Promise<string>;

  spSymbol(overrides?: CallOverrides): Promise<string>;

  spSymbolSlaId(
    slaId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  testingOracleID(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateTimestamp(
    receivedTimestampMilliseconds: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillSLI(
      _requestId: BytesLike,
      _chainlinkResponse: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fulfillsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getDataServiceId(overrides?: CallOverrides): Promise<string>;

    getOracleForSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<number>;

    jobId(overrides?: CallOverrides): Promise<string>;

    lpName(overrides?: CallOverrides): Promise<string>;

    lpSymbol(overrides?: CallOverrides): Promise<string>;

    lpSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    messengerPrecision(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestSLI(
      _periodId: BigNumberish,
      _slaAddress: string,
      _ownerApproval: boolean,
      _callerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requestsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    retryRequest(
      _slaAddress: string,
      _periodId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setChainlinkJobID(
      arg0: BytesLike,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDataFeedForSLA(
      _slaAddress: string,
      _oracle: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setSLARegistry(overrides?: CallOverrides): Promise<void>;

    slaRegistryAddress(overrides?: CallOverrides): Promise<string>;

    spName(overrides?: CallOverrides): Promise<string>;

    spSymbol(overrides?: CallOverrides): Promise<string>;

    spSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    testingOracleID(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DataFeedSetForSLA(address,bytes32)"(
      slaAddress?: string | null,
      oracle?: BytesLike | null
    ): TypedEventFilter<
      [string, string],
      { slaAddress: string; oracle: string }
    >;

    DataFeedSetForSLA(
      slaAddress?: string | null,
      oracle?: BytesLike | null
    ): TypedEventFilter<
      [string, string],
      { slaAddress: string; oracle: string }
    >;

    "JobIdModified(address,bytes32,uint256)"(
      owner?: string | null,
      jobId?: null,
      fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; jobId: string; fee: BigNumber }
    >;

    JobIdModified(
      owner?: string | null,
      jobId?: null,
      fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; jobId: string; fee: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "SLIReceived(address,uint256,bytes32,bytes32)"(
      slaAddress?: string | null,
      periodId?: null,
      requestId?: BytesLike | null,
      chainlinkResponse?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      {
        slaAddress: string;
        periodId: BigNumber;
        requestId: string;
        chainlinkResponse: string;
      }
    >;

    SLIReceived(
      slaAddress?: string | null,
      periodId?: null,
      requestId?: BytesLike | null,
      chainlinkResponse?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      {
        slaAddress: string;
        periodId: BigNumber;
        requestId: string;
        chainlinkResponse: string;
      }
    >;

    "SLIRequested(address,uint256,bytes32)"(
      caller?: string | null,
      requestsCounter?: null,
      requestId?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; requestsCounter: BigNumber; requestId: string }
    >;

    SLIRequested(
      caller?: string | null,
      requestsCounter?: null,
      requestId?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; requestsCounter: BigNumber; requestId: string }
    >;
  };

  estimateGas: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillSLI(
      _requestId: BytesLike,
      _chainlinkResponse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fulfillsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDataServiceId(overrides?: CallOverrides): Promise<BigNumber>;

    getOracleForSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUniqueSignersThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    jobId(overrides?: CallOverrides): Promise<BigNumber>;

    lpName(overrides?: CallOverrides): Promise<BigNumber>;

    lpSymbol(overrides?: CallOverrides): Promise<BigNumber>;

    lpSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    messengerPrecision(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestSLI(
      _periodId: BigNumberish,
      _slaAddress: string,
      _ownerApproval: boolean,
      _callerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestsCounter(overrides?: CallOverrides): Promise<BigNumber>;

    retryRequest(
      _slaAddress: string,
      _periodId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setChainlinkJobID(
      arg0: BytesLike,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDataFeedForSLA(
      _slaAddress: string,
      _oracle: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSLARegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    slaRegistryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    spName(overrides?: CallOverrides): Promise<BigNumber>;

    spSymbol(overrides?: CallOverrides): Promise<BigNumber>;

    spSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testingOracleID(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aggregateValues(
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    extractTimestampsAndAssertAllAreEqual(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fulfillSLI(
      _requestId: BytesLike,
      _chainlinkResponse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fulfillsCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAuthorisedSignerIndex(
      signerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDataServiceId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOracleForSLA(
      _slaAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUniqueSignersThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    jobId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpSymbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    messengerPrecision(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestSLI(
      _periodId: BigNumberish,
      _slaAddress: string,
      _ownerApproval: boolean,
      _callerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestsCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    retryRequest(
      _slaAddress: string,
      _periodId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setChainlinkJobID(
      arg0: BytesLike,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDataFeedForSLA(
      _slaAddress: string,
      _oracle: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSLARegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    slaRegistryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    spName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spSymbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spSymbolSlaId(
      slaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testingOracleID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateTimestamp(
      receivedTimestampMilliseconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
